stages:
  - features

release_features:
  stage: features
  tags:
    - sam-docker
  image: docker.io/library/node:24-bookworm
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - features/*
        - .gitlab-ci.yml
    - when: never
  variables:
    DEVCONTAINERS_OCI_AUTH: "${CI_REGISTRY}|gitlab-ci-token|${CI_JOB_TOKEN}"
  script:
    - npm install -g @devcontainers/cli
    - devcontainer features publish -r ${CI_REGISTRY} -n ${CI_PROJECT_PATH} "${CI_PROJECT_DIR}/features/ros"
